apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: {{index . "namespace"}}
spec:
  serviceAccountName: {{index . "serviceAccountName"}}
  releaseName: nextcloud
  chart:
    spec:
      chart: nextcloud
      version: "3.3.3"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
  interval: 5m
  install:
    remediation:
      retries: -1
  uninstall:
    timeout: 5m
  test:
    enable: false
  values:
    ingress:
      {{- if and (index . "isNginxInstalled") (index . "isDomainInstalled") }}
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: 100m
      {{- else }}
      enable: false
      {{- end }}
      {{- if and (index . "isNginxInstalled") (index . "isDomainInstalled") (index . "isCertManagerInstalled") }}
      tls:
        - secretName: nextcloud-cert
          hosts:
            - nextcloud.{{ index . "domain"}}
      {{- end }}
    nextcloud:
      {{- if index . "isDomainInstalled" }}
      host: nextcloud.{{ index . "domain"}}
      {{- end }}
      existingSecret:
        enabled: true
        secretName: nextcloud-admin
        usernameKey: username
        passwordKey: password
      {{- if or (index . "isPostgresqlInstalled") (index . "isRedisInstalled") (index . "isSmtpServerInstalled") }}
      extraEnv:
      {{- end }}
      {{- if index . "isPostgresqlInstalled" }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgres-password
      {{- end }}
      {{- if index . "isRedisInstalled" }}
        - name: REDIS_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password-secret
              key: redis-password
        - name: REDIS_HOST
          value: {{ index . "redisName"}}-master.{{ index . "redisNamespace"}}
        - name: REDIS_HOST_PORT
          value: "6379"
      {{- end }}
      {{- if index . "isSmtpServerInstalled" }}
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: host
        - name: MAIL_DOMAIN
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: domain
        - name: MAIL_FROM_ADDRESS
          value: noreply
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: port
        - name: SMTP_SECURE
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: secure
        - name: SMTP_NAME
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: password
      {{- end }}
      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array (
            'overwriteprotocol' => 'https',
            'overwrite.cli.url' => 'https://nextcloud.{{ index . "domain"}}',
            'filelocking.enabled' => 'true',
            'loglevel' => '2',
            'enable_previews' => true,
            'trusted_domains' =>
              [
                'nextcloud',
                'nextcloud.{{ index . "domain"}}'
              ]
          );
      {{- if (index . "isRedisInstalled") }}
        redis.config.php: |-
          <?php
          $CONFIG = array (
            'memcache.local' => '\\OC\\Memcache\\Redis',
            'memcache.distributed' => '\OC\Memcache\Redis',
            'memcache.locking' => '\OC\Memcache\Redis',
            'redis' => array(
              'host' => getenv('REDIS_HOST'),
              'port' => getenv('REDIS_HOST_PORT') ?: 6379,
              'password' => getenv('REDIS_HOST_PASSWORD')
            )
          );
      defaultConfigs:
        redis.config.php: false
      {{- end }}
    persistence:
      enabled: true
      size: 4Gi
      nextcloudData:
        enabled: true
        size: {{ or (index . "size") "8Gi" }}
    cronjob:
      annotations: {}
      curlInsecure: false
      enabled: true
      failedJobsHistoryLimit: 5
      image: {}
      schedule: "*/5 * * * *"
      successfulJobsHistoryLimit: 2
    {{- if index . "isPostgresqlInstalled" }}
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: {{ index . "postgresqlName"}}.{{ index . "postgresqlNamespace"}}.svc.cluster.local:5432
      user: postgres
      database: nextcloud
      password: "xxx"
    {{- end }}
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Deployment
              name: nextcloud
            patch:
              - op: replace
                path: "/spec/template/spec/containers/1/resources/requests/cpu"
                value: "100m"
              - op: replace
                path: "/spec/template/spec/containers/1/resources/requests/memory"
                value: "128Mi"
    {{- if index . "isPostgresqlInstalled" }}
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: nextcloud
            spec:
              template:
                spec:
                  initContainers:
                    - name: "initdb"
                      image: "docker.io/bitnami/postgresql:11.3.0"
                      command: ["/bin/bash", "-c"]
                      args: ['echo $SQL > /tmp/init.sql; psql -f /tmp/init.sql --host {{ index . "postgresqlName"}}.{{ index . "postgresqlNamespace"}} -U postgres']
                      env:
                        - name: PGPASSWORD
                          valueFrom:
                            secretKeyRef:
                              name: postgresql-secret
                              key: postgres-password
                        - name: SQL
                          value: "select 'create database nextcloud' where not exists (select from pg_database where datname = 'nextcloud')\\gexec"
    {{- end}}
